name: .NET Docker CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Stop existing containers
      run: |
        cd $GITHUB_WORKSPACE
        docker-compose down || true

    - name: Remove old images (optional - giải phóng dung lượng)
      run: |
        docker image prune -af --filter "label=project=hotelmanagement" || true

    - name: Build and start Docker containers
      run: |
        cd $GITHUB_WORKSPACE
        docker-compose up -d --build

    - name: Wait for application to be ready
      run: |
        echo "⏳ Đợi ứng dụng khởi động..."
        sleep 30
        
    - name: Check container status
      run: |
        echo "📊 Trạng thái containers:"
        docker-compose ps
        
    - name: Show application logs
      run: |
        echo "📝 Logs của webapp:"
        docker-compose logs --tail=50 webapp

    - name: Health check
      run: |
        echo "🏥 Kiểm tra health..."
        max_attempts=10
        attempt=0
        
        while [ $attempt -lt $max_attempts ]; do
          if curl -f http://localhost:5153/health 2>/dev/null; then
            echo "✅ Application is healthy!"
            exit 0
          fi
          
          attempt=$((attempt + 1))
          echo "⏳ Attempt $attempt/$max_attempts failed, retrying in 5s..."
          sleep 5
        done
        
        echo "❌ Health check failed after $max_attempts attempts"
        docker-compose logs webapp
        exit 1

    - name: Cleanup old Docker resources
      if: success()
      run: |
        echo "🧹 Dọn dẹp Docker resources..."
        docker image prune -af --filter "until=24h"
        docker volume prune -f

    - name: Send notification on failure
      if: failure()
      run: |
        echo "❌ Deploy failed! Check logs above."
        docker-compose logs --tail=100 webapp